# docker-compose.test.yml (v3.0 - Dev Environment)

services:
  obu-ocr-app:
    # 在开发时，我们通常使用build来实时构建，或者使用一个固定的基础镜像
    build: .
    image: obu-ocr-service-dev:v3.0
    container_name: obu-ocr-container-dev
    restart: unless-stopped
    ports:
      - "5000:5000"

    volumes:
      # 开发模式的核心：挂载所有代码和配置，实现热重载
      - .:/app

    # 注入环境变量，用于连接数据库
    env_file:
      - .env