version: '3.8'

services:
  obu-ocr-app:
    # 1. 使用预先构建好的镜像，而不是在运行时构建或挂载代码
    image: obu-ocr-service:v1.0
    container_name: obu-ocr-container
    restart: always
    ports:
      - "5000:5000"

    # 2. 【核心性能配置】将容器绑定到指定的CPU核心
    #    - cpuset: '0-3' 表示容器将只能使用CPU核心0, 1, 2, 3。
    #    - 这可以避免CPU资源争抢和不必要的上下文切换，提供稳定性能。
    #    - 注意：请根据您服务器的实际CPU核心数量和规划来修改此值。
    #      您可以通过 `lscpu` 命令查看服务器的CPU信息。
    # cpuset: '0-3'

    # 3. 【核心性能配置】内存限制
    #    - memory: '4g' 是一个硬性限制，容器使用的内存不能超过4GB。
    #    - memory_reservation: '2g' 是一个软性保证，Docker会确保容器至少有2GB可用内存。
    #    - 这可以防止内存泄漏耗尽服务器资源，并保证服务有足够的启动内存。
    # mem_limit: 4g
    # mem_reservation: 2g

    # 4. 【安全配置】通过环境变量注入敏感信息
    #    - 不再将密码硬编码在代码中。
    #    - 推荐使用 .env 文件来管理这些值，避免直接写入compose文件。

    volumes:
      # 将代码作为“数据”挂载，实现快速更新
      - .:/app

      # 将运行时数据目录分离
      - ./uploads:/app/uploads
      - ./process_photo:/app/process_photo
      - ./log:/app/log