version: '3.8'

services:
  obu-ocr-app:
    # 使用我们设计的版本化命名
    build: .
    image: obu-ocr-service:${IMAGE_VERSION:-dev}

    container_name: obu-ocr-container-dev
    restart: unless-stopped
    ports:
      - "5000:5000"

    volumes:
      # 将代码作为“数据”挂载，实现快速更新
      - .:/app

      # 将运行时数据目录分离
      - ./uploads:/app/uploads
      - ./process_photo:/app/process_photo
      - ./log:/app/log

    # 注入环境变量，用于连接数据库
    env_file:
      - .env