# docker-compose.prod.yml (FINAL - Original Architecture)
version: '3.8'

services:
  obu-ocr-app:
    # 使用脚本中定义的、经过测试的版本
    image: obu-ocr-service:${IMAGE_VERSION}

    container_name: obu-ocr-container-prod
    restart: always
    ports:
      - "5000:5000"

    # 资源限制：现在所有的资源都分配给这一个服务
    cpuset: '${APP_CORES_CPUSET}'
    mem_limit: '${APP_MEM_LIMIT}'
    mem_reservation: '${APP_MEM_RESERVATION}'

    # 挂载配置文件和数据卷
    volumes:
      - ./config.py:/app/config.py
      - ./model:/app/model:ro
      - ./uploads:/app/uploads
      - ./process_photo:/app/process_photo
      - ./log:/app/log

    # 注入环境变量
    env_file:
      - .env